server:
  port: 12100
feign:
  client:
    config:
      defalt:
        readTimeout: 600000
        connectTimeout: 600000
spring:
  redis:
    # Redis服务器地址
    host: 121.37.149.40
    #Redis服务器连接端口
    port: 6379
    password: XMUwwf@4288
    # 连接超时时间（毫秒）
    timeout: 5000
    surviveTime: 30000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.149.40:8848
  application:
    name: ImageService
  datasource:
    url: jdbc:mysql://123.60.75.90:3306/opus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
qiniu:
  accessKey: KzK8R-WoPzmZxJYLHsDUjnUK2DKnhsKBHhOeBJVM
  secretKey: qMDpw8obgKLZT46HMJXPh0t0OzOC5Vt7KEBzqGhu
  bucket: xmuwwf-images
  zone: up-cn-east-2.qiniup.com
  domain: rau38waqa.bkt.clouddn.com
mybatis:
  mapper-locations: classpath:/mapper/*xml
  type-aliases-package: cn.edu.xmu.wwf.opus.imageservice.model
  configuration:
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 121.37.149.40:9876
  producer:
    isOnOff: on
    group: opus-image-group
    groupName: opus-image-group
    namesrvAddr: 121.37.149.40:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2






