server:
  port: 12138
  servlet:
    encoding:
      charset: utf-8
feign:
  client:
    config:
      defalt:
        readTimeout: 600000
        connectTimeout: 600000
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
spring:
  redis:
    # Redis服务器地址
    host: 121.37.149.40
    #Redis服务器连接端口
    port: 6379
    password: XMUwwf@4288
    # 连接超时时间（毫秒）
    timeout: 5000
    surviveTime: 30000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
  http:
    encoding:
      charset: utf-8
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.149.40:8848
  application:
    name: ArtworkService
  datasource:
    url: jdbc:mysql://123.60.75.90:3306/opus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*xml
  type-aliases-package: cn.edu.xmu.wwf.opus.artworkservice.model
  configuration:
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 121.37.149.40:9876
  producer:
    isOnOff: on
    group: opus-artwork-group
    groupName: opus-artwork-group
    namesrvAddr: 121.37.149.40:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
pagehelper:
  #配置四項 hprs
  helper-dialect: mysql  #分页助手方言：mysql
  params: count=countSql  #为了支持 startPage(Object params) 方法
  support-methods-arguments: true  #支持通过 Mapper 接口参数来传递分页参数，默认值 false
  reasonable: true #分页合理化参数，默认值为 false,页码不为负，不超总页码