server:
  port: 12101
feign:
  client:
    config:
      defalt:
        readTimeout: 600000
        connectTimeout: 600000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.149.40:8848
  application:
    name: CategoryService
  datasource:
    url: jdbc:mysql://123.60.75.90:3306/opus
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*xml
  type-aliases-package: cn.edu.xmu.wwf.opus.artworkservice.model
  configuration:
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 121.37.149.40:9876
  producer:
    isOnOff: on
    group: opus-artwork-group
    groupName: opus-artwork-group
    namesrvAddr: 121.37.149.40:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
pagehelper:
  #配置四項 hprs
  helper-dialect: mysql  #分页助手方言：mysql
  params: count=countSql  #为了支持 startPage(Object params) 方法
  support-methods-arguments: true  #支持通过 Mapper 接口参数来传递分页参数，默认值 false
  reasonable: true #分页合理化参数，默认值为 false,页码不为负，不超总页码
